<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <NoWarn>NU1605;NU1202</NoWarn>
    <OutputPath>$(MSBuildProjectDirectory)\..\..\..\..\..\build\windows\avox\install\AMD64\$(Configuration)\</OutputPath>
    <BaseOutputPath>$(OutputPath)</BaseOutputPath>
    <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
  </PropertyGroup>

  <ItemGroup>
    <AvaloniaResource Include="Assets\**" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Avalonia.Desktop" />
    <PackageReference Include="Avalonia.Diagnostics">
      <IncludeAssets Condition="'$(Configuration)' != 'Debug'">None</IncludeAssets>
      <PrivateAssets Condition="'$(Configuration)' != 'Debug'">All</PrivateAssets>
    </PackageReference>
    <PackageReference Include="HarfBuzzSharp" NoWarn="NU1605;NU1202">
      <PrivateAssets>all</PrivateAssets>
      <ExcludeAssets>none</ExcludeAssets>
    </PackageReference>
    <PackageReference Include="MicroCom.Runtime">
      <PrivateAssets>all</PrivateAssets>
      <ExcludeAssets>none</ExcludeAssets>
    </PackageReference>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\AvaPlayer\AvaPlayer.csproj" />
  </ItemGroup>
</Project>