#!/bin/bash

WEBRTC_DIR="/home/zhouxin/work/webrtc"
BUILD_TYPE="$1"
BUILD_DIR="$WEBRTC_DIR/build/android/$BUILD_TYPE"

# envsetup不能用bash执行,需要source执行,永久改变环境变量
echo "首次构建android请先执行: bash $WEBRTC_DIR/src/build/install-build-deps.sh --android 与 source $WEBRTC_DIR/src/build/android/envsetup.sh"

if [ "$BUILD_TYPE" != "debug" ] && [ "$BUILD_TYPE" != "release" ]; then
    echo "Error: Build type must be debug or release"
    exit 1
fi

echo "Building WebRTC Android $BUILD_TYPE static library..."
cd "$WEBRTC_DIR/src"

IS_DEBUG=false
if [ "${BUILD_TYPE,,}" == "debug" ]; then
    IS_DEBUG=true
fi

# gn选项可以在$WEBRTC_DIR/src下使用gn args --list "$WEBRTC_DIR"查看
# webrtc团队越来越倾向于使用use_custom_libcxx=true下编译
# 其use_custom_libcxx=false需配合use_clang_modules=false use_autogenerated_modules=false并改一些编译脚本才可通过
# https://www.nxrte.com/jishu/webrtc/61097.html
# android_ndk_root="/opt/android-sdk/ndk/21.0.6113669" 21.0.6113669 26.1.10909125
# android在NDK17后只使用clang编译
GN_ARGS="target_os=\"android\" default_min_sdk_version=28 android_ndk_api_level=23 target_cpu=\"arm64\" is_debug=$IS_DEBUG use_rtti=true use_custom_libcxx=false use_custom_libunwind=false use_clang_modules=false use_autogenerated_modules=false rtc_enable_protobuf=false libyuv_use_sme=false rtc_include_tests=false rtc_use_h265=true proprietary_codecs=true rtc_build_tools=false android_static_analysis=\"off\" is_component_build=false treat_warnings_as_errors=false"

echo "Generating GN configuration..."
gn gen "$BUILD_DIR" --args="$GN_ARGS"

echo "Building static library..."
ninja -C "$BUILD_DIR" webrtc

if [ $? -ne 0 ]; then
    echo "Build failed"
    exit 1
fi

# 无符号轻量版: 必须用NDK的llvm-strip, GNU strip认不了bitcode成员(wrapper.o)
cp "$BUILD_DIR/obj/libwebrtc.a" "$BUILD_DIR/obj/libwebrtc_nosym.a"
"$ANDROID_NDK_PATH/toolchains/llvm/prebuilt/linux-x86_64/bin/llvm-strip" --strip-debug "$BUILD_DIR/obj/libwebrtc_nosym.a"

echo "Build successful!"
echo "Static library(带符号): $BUILD_DIR/obj/libwebrtc.a"
echo "Static library(无符号): $BUILD_DIR/obj/libwebrtc_nosym.a"
echo "Headers: $BUILD_DIR/gen"
echo "拷贝到SDK依赖目录: cp $BUILD_DIR/obj/libwebrtc*.a <avc_library>/build/android/release/"