require 'fileutils'
require 'pathname'

# 确保使用合适的 CocoaPods 版本
platform :ios, '12.0'
# 以 .framework 的形式打包
# use_frameworks!

# 指定 Xcode 工作区路径，根据实际情况修改
workspace 'testpod'
# 从当前目录出发，使用相对路径指定 testbed.xcodeproj 的位置
project 'testpod'

avoxsdk_path = File.expand_path('../../../../', __FILE__)
avoxsdk_podspec_path = File.join(avoxsdk_path, 'avox.podspec')
if File.exist?(avoxsdk_podspec_path)
  def avoxsdk(path)
    # 使用 :path 参数引用本地的 avoxsdk.podspec
    pod 'avox', :path => path
  end
else
  raise "avoxsdk.podspec not found at #{avoxsdk_podspec_path}"
end

# 定义target,需要在project中有的项目名
target 'testpod' do  
  # 对应上面对应的函数
  avoxsdk(avoxsdk_path)
end