#version 450

layout (local_size_x = 16, local_size_y = 16) in;// gl_WorkGroupSize
layout (binding = 0, rgba8) uniform readonly image2D inTex;
layout (binding = 1) uniform sampler2D inSampler;
layout (binding = 2, rgba8) uniform image2D outTex;

layout (std140, binding = 3) uniform UBO {
    float blend;
} ubo;

void main(){
    ivec2 uv = ivec2(gl_GlobalInvocationID.xy);
    ivec2 size = imageSize(inTex);
    if(uv.x >= size.x || uv.y >= size.y){
        return;
    } 
    vec2 suv = (vec2(uv)+vec2(0.5f))/vec2(size);  
    vec4 color = imageLoad(inTex,uv); 
    vec4 color1 = textureLod(inSampler, suv,0);
    // 如果自己alpha通道是0,全给对面
    // vec3 bcolor = mix(color.rgb,color1.rgb,1.0f - color.a);
    // vec3 bcolor1 = mix(color1.rgb,color.rgb,1.0f - color1.a);
    vec4 result = vec4(mix(color.rgb,color1.rgb,ubo.blend),color.a);
    imageStore(outTex,uv,result);     
}