#version 450

layout(local_size_x = 16, local_size_y = 16) in; // gl_WorkGroupSize

layout(binding = 0) uniform sampler2D inSampler;
layout(binding = 1, rgba8) uniform image2D outTex;

layout(std140, binding = 2) uniform UBO {
  float leftOffset;
  float topOffset;
  float x;
  float y;
  float z;
  float w;
}
ubo;

void main() {
  ivec2 uv = ivec2(gl_GlobalInvocationID.xy);
  ivec2 size = imageSize(outTex);
  if (uv.x >= size.x || uv.y >= size.y) {
    return;
  }
  vec2 suv = (vec2(uv) + vec2(0.5f)) / vec2(size) +
             vec2(ubo.leftOffset, ubo.topOffset);
  vec2 clampedUV = clamp(suv, vec2(0.0), vec2(1.0));
  // UV是否越界
  vec2 isOutside = step(suv, vec2(0.0)) + step(vec2(1.0), suv);
  vec4 color = textureLod(inSampler, clampedUV, 0);
  // 边界处理
  vec4 fillColor = vec4(ubo.x,ubo.y,ubo.z,ubo.w);
  vec4 result = mix(color, fillColor, dot(isOutside, vec2(1.0)));  
  imageStore(outTex, uv, result);
}