#version 450

layout(local_size_x = 16, local_size_y = 16) in; // gl_WorkGroupSize
// 视频帧
layout(binding = 0, rgba8) uniform readonly image2D inTex;
// canvas R8（大小 = 帧大小/tscale），通过 sampler 采样自动双线性插值
layout(binding = 1) uniform sampler2D inTex2;
// 输出
layout(binding = 2, rgba8) uniform image2D outTex;

layout(std140, binding = 3) uniform UBO {
  float fcolorx;
  float fcolory;
  float fcolorz;
  // 不透明度,0-1之间,0完全不透明,1完全透明
  float opacity;
}
ubo;

void main() {
  ivec2 id = ivec2(gl_GlobalInvocationID.xy);
  ivec2 size = imageSize(outTex);
  if (id.x >= size.x || id.y >= size.y)
    return;
  // 首先从输入纹理读取基础颜色
  vec4 color = imageLoad(inTex, id);
  // 归一化 UV 坐标，自动映射 canvas 到帧
  vec2 uv = vec2(id.x + 0.5, id.y + 0.5) / vec2(size);
  float frame = textureLod(inTex2, uv, 0.0).r;
  if (frame > 0.0) {
    vec3 fcolor = vec3(ubo.fcolorx, ubo.fcolory, ubo.fcolorz);
    color.rgb = mix(color.rgb, fcolor.rgb, frame * (1.0f - ubo.opacity));
  }
  // 存储到输出纹理
  imageStore(outTex, id, color);
}
