#version 450

layout (local_size_x = 16, local_size_y = 16) in;// gl_WorkGroupSize

layout (binding = 0, r16ui) uniform readonly uimage2D inTex;
layout (binding = 1, r16ui) uniform uimage2D outTex;

layout (std140, binding = 2) uniform UBO {
    // 1
    int bLinear;
    // 0
    float fx;
    float fy;
} ubo;

void main(){
    ivec2 uv = ivec2(gl_GlobalInvocationID.xy);
    ivec2 size = imageSize(outTex); 
    ivec2 inSize = imageSize(inTex);   
    if(uv.x >= size.x || uv.y >= size.y){
        return;
    }    
    float r = 0.0;
    float inX = uv.x * ubo.fx;
    float inY = uv.y * ubo.fy;
    int x1 = int(inX);
    int y1 = int(inY);
    int x2 = x1+1;
    int y2 = y1+1;
    int x2_read = min(x2,inSize.x-1);
    int y2_read = min(y2,inSize.y-1);

    uint ri = imageLoad(inTex,ivec2(x1,y1)).r;
    float fi = float(ri);
    r = r + fi*((x2-inX)*(y2-inY));

    ri = imageLoad(inTex,ivec2(x2_read,y1)).r;
    fi = float(ri);
    r = r + fi*((inX- x1)*(y2-inY));

    ri = imageLoad(inTex,ivec2(x1,y2_read)).r;
    fi = float(ri);
    r = r + fi*((x2-inX)*(inY-y1));

    ri = imageLoad(inTex,ivec2(x2_read,y2_read)).r;
    fi = float(ri);
    r = r + fi*((inX- x1)*(inY-y1));   

    uint rri = uint(r);
    imageStore(outTex,uv,uvec4(rri)); 
}
