#version 450

layout(local_size_x = 16, local_size_y = 16) in; // gl_WorkGroupSize

// ADDMAP 相当于原图UV添加MAP后,如添加畸变,反正则去畸变
layout(binding = 0) uniform sampler2D inSampler;
layout(binding = 1) uniform sampler2D inXSampler;
layout(binding = 2) uniform sampler2D inYSampler;

layout(binding = 3, rgba8) uniform image2D outTex;

layout(std140, binding = 4) uniform UBO {
  int mapWidth;
  int mapHeight;
}
ubo;

void main() {
  ivec2 uv = ivec2(gl_GlobalInvocationID.xy);
  ivec2 size = imageSize(outTex);
  if (uv.x >= size.x || uv.y >= size.y) {
    return;
  }
  vec2 suv = (vec2(uv) + vec2(0.5f)) / vec2(size);
  float xalpha = textureLod(inXSampler, suv, 0).r;
  float yalpha = textureLod(inYSampler, suv, 0).r;
  // 正常图UV对应的畸变图上UV
  vec2 mapUV =
      (vec2(xalpha, yalpha) + vec2(0.5)) / vec2(ubo.mapWidth, ubo.mapHeight);
#if ADDMAP
  // 添加畸变(在正常的图取正常UV的颜色放入畸变UV图上) distort
  // 畸变UV做为输出,很难处理,现参考UE4做法(近似正常,小计算量)
  mapUV = suv - mapUV;
#endif
  vec2 clampedUV = clamp(mapUV, vec2(0.0), vec2(1.0));
  vec2 isOutside = step(mapUV, vec2(0.0)) + step(vec2(1.0), mapUV);
  vec4 color = textureLod(inSampler, clampedUV, 0);
  vec4 result = mix(color, vec4(0.0), dot(isOutside, vec2(1.0))); 
  // vec4 result = textureLod(inSampler, mapUV,0); 
  imageStore(outTex, uv, result);
}