<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <NoWarn>NU1605;NU1202</NoWarn>
    <OutputPath>$(MSBuildProjectDirectory)\..\..\..\..\build\windows\avplay\install\AMD64\$(Configuration)\</OutputPath>
    <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
    <Nullable>disable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <AvaloniaResource Include="Assets\**" />
  </ItemGroup>

  <ItemGroup>
    <Compile Include="..\..\..\..\swig\csharp\files\*.cs" Link="swig\%(Filename).cs" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Avalonia.Desktop" />
    <PackageReference Include="Avalonia.Themes.Fluent" />
    <PackageReference Include="Avalonia.Fonts.Inter" />
    <PackageReference Include="Avalonia.Controls.DataGrid" />
    <PackageReference Include="MessageBox.Avalonia" />
    <PackageReference Include="HarfBuzzSharp" />
    <PackageReference Include="MicroCom.Runtime" />
  </ItemGroup>
</Project>
